gke yml

diff --git a/.github/workflows/cml.yaml b/.github/workflows/cml.yaml
--- a/.github/workflows/cml.yaml
+++ b/.github/workflows/cml.yaml
@@ -47,3 +47,96 @@ jobs:
         run: |
           # DVC repro ejecutará la etapa "train" y, por lo tanto, el script train.py.
           dvc repro
+  build-and-push:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      - name: Set up Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: '3.11'
+      - name: Install DVC
+        uses: iterative/setup-dvc@v1
+      - name: Pull model from DagsHub with DVC
+        env:
+          DAGSHUB_API_KEY: ${{ secrets.DAGSHUB_API_KEY }}
+        run: |
+          git config --global user.email "202108204@alu.comillas.edu"
+          git config --global user.name "NatLey30"
+          dvc remote modify origin --local access_key_id $DAGSHUB_API_KEY
+          dvc remote modify origin --local secret_access_key $DAGSHUB_API_KEY
+          dvc pull -r origin
+      - name: Verify model exists
+        run: |
+          ls -lh model.pkl || (echo "Model not found" && exit 1)
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+      - name: Log in to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+      - name: Build and push API image
+        uses: docker/build-push-action@v6
+        with:
+          context: .
+          file: ./Dockerfile
+          push: true
+          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mlops-api:latest
+      - name: Build and push Web image
+        uses: docker/build-push-action@v6
+        with:
+          context: .
+          file: ./Dockerfile.web
+          push: true
+          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mlops-web:latest
+  deploy-to-gke:
+    needs: train-and-report
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: DVC and Python setup
+        uses: iterative/setup-dvc@v1
+      - name: Setup Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: '3.11'
+      - id: 'auth'
+        name: Authenticate to Google Cloud
+        uses: 'google-github-actions/auth@v2'
+        with:
+          credentials_json: '${{ secrets.GCP_SA_KEY }}'
+      - name: Set up gcloud CLI and kubectl
+        uses: 'google-github-actions/setup-gcloud@v2'
+        with:
+          version: 'latest'
+          install_components: 'gke-gcloud-auth-plugin'
+      - name: Get GKE credentials
+        run: gcloud container clusters get-credentials ${{vars.GKE_CLUSTER }} --zone ${{ vars.GKE_ZONE }} --project ${{vars.GCP_PROJECT_ID }}
+      - name: DVC Pull
+        env:
+          DAGSHUB_API_KEY: ${{ secrets.DAGSHUB_API_KEY }} # Las credenciales de Dagshub son necesarias para acceder al almacenamiento remoto
+        run: |
+          dvc remote modify origin --local access_key_id $DAGSHUB_API_KEY
+          dvc remote modify origin --local secret_access_key $DAGSHUB_API_KEY
+          dvc pull -r origin
+      - name: Install dependencies
+        run: |
+          python3 -m pip install --upgrade pip
+          pip install -r requirements.txt
+      - name: Configure Docker to use GCR
+        run: gcloud auth configure-docker
+      - name: Build and Push Docker Image
+        run: |
+          docker build -t gcr.io/${{ vars.GCP_PROJECT_ID
+          }}/mlops-api:latest .
+          docker push gcr.io/${{ vars.GCP_PROJECT_ID
+          }}/mlops-api:latest
+      - name: Deploy to GKE
+        run: |
+          kubectl apply -f deployment.yaml
+          kubectl apply -f service.yaml
